name: Build Everything TGW

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.3.8'
        default: 'v0.3.8'
        required: true
        type: string

permissions:
  contents: write

jobs:          
  build_textgen_wheels_linux:
    name: CUDA Wheels Linux
    uses: ./.github/workflows/build-wheels-oobabooga.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:ubuntu-22.04'

  build_wheels_cpu:
    name: CPU-only Wheels
    uses: ./.github/workflows/build-wheels-cpu.yml
    with:
      version: ${{ inputs.version }}
      
